server:
  port: 10001
spring:
  application:
    name: mall-customer-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: mall
        namespace: ffd07fc8-0c2a-4c04-af37-03c28671a1a0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall-customer?verifyServerCertificate=false&useSSL=false
    username: root
    password: shiyunhao123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl